language: go

go:
  - 1.8

go_import_path: github.com/mysql-monitor

script:
  - make build

matrix:
  include:
  - go: 1.8
    install:
      - go get github.com/mattn/goveralls
    env:
      - TRAVIS_COVERAGE=1
    script:
      - make build
    after_success:
      - travis_wait make travis_coverage
